title: Phil's Blog
email: your-email@example.com
description: >-
  Your site description
baseurl: "" # leave this empty for user sites
url: "https://philhosophy.github.io"
github_username: philhosophy
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

future: true
